### ISSUE TITLE
Set up a github action using hatch to release to PyPI

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/pyosMeta#100]
Automate the release to PyPI using hatch.

To approach this issue, consult the hatch documentation and recommended GitHub action.

This task will finish and close #82.

**Comment by lwasser** [comment]
yay thanks @willingc i have [this workflow](https://github.com/stravalib/stravalib/blob/main/.github/workflows/push-pypi.yml) that publishes using setuptools_Scm (which hatch is using under the hood). 

So i think the big changes for this are

- [x] setup a trusted workflow in pypi (this is just easier to maintain than worrying about tokens and such) and preferred. 
- [ ] switch the build step to hatch build rather than using pypa build (pr opening in just a few)
