### ISSUE TITLE
Prep March 2024 release

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/pyosMeta#144]
Let's begin release this package at the end of each month.

March 2024 Release Prep Checklist
- [x] Create milestone for release
- [x] Assign issues to the milestone
- [x] Test release
- [x] Update CHANGELOG.md and create a new unreleased section: @willingc
- [x] Release to PyPI @lwasser and @willingc 
- [x] Test PyPI release installation
- [x] Announce the release on social media
- [x] Close March 2024 milestone @willingc 
- [x] Open April 2024 milestone with a due date 2024-04-30: @willingc

**Comment by lwasser** [comment]
hi @willingc this looks great. i just opened the pr i've wanted to open to separate our release build into two steps. i can't test it however until we publish!! 🤞 

in the meantime the one last issue had one element that will take more time to implement - using sigstore to sign our releases. so i suggest we move that to another release later. But the pr opened now #145 addresses the last of the march milestone tasks!! and we will be ready to test out the changes this week when we release. 

i also removed the test pypi publication step because pydantic is not updated on test pypi which means out package will never actually run properly. The test pypi build is also breaking now so in the open pr i removed that step from our build. let's just use pypi. What we can do is create a pre release before creating a full release. i'll go ahead and merge the open pr and test that out today / tomorrow!

**Comment by willingc** [comment]
Let's plan on releasing when we chat on Friday @lwasser.

**Comment by lwasser** [comment]
ok sounds good @willingc !! ✨

**Comment by lwasser** [comment]
release created!!! 🚀
